# azure-pipelines.yml
# Reusable public CI/CD pipeline for open-source projects

trigger:
  branches:
    include:
      - main
      - master
      - develop

pr:
  branches:
    include:
      - '*'

variables:
  buildConfiguration: 'Release'
  vmImageName: 'ubuntu-latest'

stages:

- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
    - script: echo "Building the project..."
      displayName: 'Run Build Script'
    - script: echo "Add your build steps here (e.g., dotnet build, npm install, etc.)"
      displayName: 'Example Build Command'

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: TestJob
    displayName: 'Test Job'
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
    - script: echo "Running unit tests..."
      displayName: 'Run Tests'
    - script: echo "Add your test commands here (e.g., dotnet test, npm test, etc.)"
      displayName: 'Example Test Command'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Test
  condition: succeeded()
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
    - script: echo "Deploying the project..."
      displayName: 'Deploy Placeholder'
    - script: echo "Add deployment steps here (e.g., Azure CLI deploy, ARM template deployment)"
      displayName: 'Example Deployment Command'
